# Bun Configuration File (bunfig.toml)

[install]
# Use exact versions for better reproducibility
exact = true
# Enable frozen lockfile
frozen = true

[install.cache]
# Enable global cache
dir = "~/.bun/cache"
enabled = true

[runtime]
# Use ESM by default
module = "module"

[debug]
# Enable source maps in development
sourcemap = true